#!/bin/sh
_brew_file_options () {
  local commands1="install brew init set_repo pull push clean update edit \
                  casklist cask_upgrade commands version help"
  local commands2="dump -i --init -s --set_repo -c --clean -u --update \
                   -e --edit --test --commands -v --version -h --help"
  local options="-f --file -F --format -r --repo -n --nolink -C \
                 -V --verbose  -U --noupdate --preupdate -y --yes"
  if [ "$1" = "1" ] || [ "$1" = "commands1" ];then
    echo $commands1
  elif [ "$1" = "2" ] || [ "$1" = "commands2" ];then
    echo $commands
  elif [ "$1" = "options" ];then
    echo $options
  elif [ "$1" = "commands" ];then
    echo $commands1 $commands2
  else
    echo $commands1 $commands2 $options
  fi
}

_brew_file_check_commands () {
  if [ "$ZSH_VERSION" != "" ];then
    local w
    w=("${words[@]:1}")
  else
    local w=("${COMP_WORDS[@]:1}")
  fi
  local cmds
  cmds=($(_brew_file_options commands))
  local c
  for c in "${w[@]}";do
    if echo " ${cmds[*]} "|grep -q " $c ";then
      echo $c
      return 0
    fi
  done
  return 1
}

_brew_file () {
  if [ "$ZSH_VERSION" != "" ];then
    local isksharrays=0
    if ! setopt|grep -q ksharrays;then
      isksharrays=1
      setopt ksharrays
    fi
    local cword=$((CURRENT-1))
    local w
    w=("${words[@]}")
  else
    local cword=$((COMP_CWORD))
    local w=("${COMP_WORDS[@]}")
  fi
  if [ $cword -gt 2 ] && [ "$1" = "brew" ] && [ "$2" = "file" ];then
    local cur=${w[cword-1]}
    local prev=${w[cword-2]}
  else
    local cur=${w[cword]}
    local prev=${w[cword-1]}
  fi
  if [ "$prev" = "-f" ];then
    if [ "$ZSH_VERSION" != "" ];then
      _files
    else
      COMPREPLY=($(compgen -f "${cur}"))
    fi
  else
    local complist=""
    if [ "$prev" = "-F" ] || [ "$prev" = "--format" ];then
      complist="file brewdler"
    elif [ "$prev" = "-V" ] || [ "$prev" = "--verbose" ];then
      complist="0 1 2"
    elif cmd=$(_brew_file_check_commands);then
      if [ "${cur:0:1}" = "-" ];then
        local minopt='-f --file -F --format -y --yes -v --verbose'
        case $cmd in
          install|pull|push|edit|-e|--edit)
            complist="$minopt --preupdate -U --noupdate";;
          brew)
            complist="$minopt";;
          init|dump|-i|--init|update|-u|--update)
            complist="$minopt -n --nolink --preupdate -U --noupdate";;
          set_repo|-s|--set_repo)
            complist="$minopt -r --repo";;
          clean|-c|--clean)
            complist="$minopt -C";;
          cask_upgrade)
            complist="-C -y --yes -v --verbose";;
          #casklist|test|commands|--commands|version|-v|--version|help|-h|--help)
          *)
            complist=""
        esac
      else
        complist=""
      fi
    else
      complist="$(_brew_file_options 1)"
    fi
    if [ "$ZSH_VERSION" != "" ];then
      compadd $(echo $complist)
    else
      COMPREPLY=($(compgen -W "$complist" -- "${cur}"))
    fi
  fi
  if [ "$ZSH_VERSION" != "" ] && [ $isksharrays -eq 1 ];then
    unsetopt ksharrays
  fi
}

if [ "$ZSH_VERSION" != "" ];then
  compdef _brew_file brew-file
else
  complete -o default -F _brew_file brew-file
fi
