#!/bin/bash
# brew command wrapper for brew-file
brew () {
  # No arguments
  if [ $# -eq 0 ];then
    command brew
    return $?
  fi

  # version check
  if [ "$ZSH_VERSION" != "" ];then
    local isksharrays=0
    if ! setopt|grep -q ksharrays;then
      isksharrays=1
      setopt ksharrays
    fi
  fi
  wrap=1
  v=($(python --version 2>&1|cut -d" " -f2|sed 's/\./ /g'))
  if [ ${v[0]} -eq 2 ];then
    if [ ${v[1]} -lt 7 ];then
      wrap=0
    elif [ ${v[1]} -eq 7 ] && [ ${v[2]} -le 6 ];then
      wrap=0
    fi
  fi
  if [ "$ZSH_VERSION" != "" ] && [ $isksharrays -eq 1 ];then
    unsetopt ksharrays
  fi

  # Do wrap
  if [ $wrap -eq 1 ];then
    # Arguments
    cmd=$1
    cmd2=$2
    cmd3=$3

    if type -a brew-file >/dev/null 2>&1;then
      case "$cmd" in
        # brew install/uninstall/tap/pip/gem
        install|reinstall|tap|pip|gem|rm|remove|uninstall|untap)
          if [ $# -gt 1 ];then
            if [ "$cmd2" != "-h" ];then
              brew-file brew "$@"
              return $?
            fi
          fi
          ;;
        # brew cask install/uninstall
        cask)
          if [ "$cmd2" = "rm" ] || [ "$cmd2" = "remove" ]\
              || [ "$cmd2" = "uninstall" ] || [ "$cmd2" = "install" ];then
            if [ $# -gt 2 ];then
              if [ "$cmd3" != "-h" ];then
                brew-file brew "$@"
                return $?
              fi
            fi
          fi
          ;;
      esac

      # Use brew-file directly for brew-file commands
      if ! echo " $(echo $(command brew commands\
          |grep -v -e "Built-in commands" -e "External commands" -e "^$")) "\
          |grep -q -- " $1 ";then
        if echo " $(brew-file commands) "|grep -q -- " $1 ";then
          brew-file "$@"
          return $?
        fi
      fi
    fi
  fi

  # Remove noinit option
  if [ "$1" = "noinit" ];then
    shift
  fi

  # Remaining command
  command brew "$@"
  return $?
}

# Wrap the brew command completion, to use the completion on `brew file`.
if (type -a _brew && type -a _brew_file) >/dev/null 2>&1;then
  _brew_completion_wrap () {
    if [ "$ZSH_VERSION" != "" ];then
      local isksharrays=0
      if ! setopt|grep -q ksharrays;then
        isksharrays=1
        setopt ksharrays
      fi
      local cword=$((CURRENT-1))
      local w
      w=("${words[@]}")
    else
      local cword=$((COMP_CWORD))
      local w=("${COMP_WORDS[@]}")
    fi
    local cur=${w[cword]}
    local first=${w[1]}
    if [ "$ZSH_VERSION" != "" ] && [ $isksharrays -eq 1 ];then
      unsetopt ksharrays
    fi
    if [ "$first" = "file" ];then
      _brew_file $*
    else
      _brew
      if [ $cword -eq 1 ];then
        if [ "$ZSH_VERSION" != "" ];then
          # Use longest brew's subcommand 'reinstall' to align with other brew commands.
          _values 'brew subcommand' 'file[manage Brewfile]' 'reinstall[install a formula anew; re-using its current options]'
        else
          COMPREPLY=($(compgen -W "${COMPREPLY[*]} file" -- "$cur"))
        fi
      fi
    fi
  }
  if [ "$ZSH_VERSION" != "" ];then
    compdef _brew_completion_wrap brew
    echo _brew_completion_wrap loaded
  else
    complete -o bashdefault -o default -F _brew_completion_wrap brew
  fi
fi
