#!/bin/sh
_brew_file_options () {
  # Using brew commands make it slow...
  #local val=$(brew file commands)
  #local commands=$(echo $val|grep 'commands: '|sed 's/commands: //')
  #local commands_hyphen=$(echo $val|grep 'commands_hyphen: '|
  #                        sed 's/commands_hyphen: //')
  #local commands=$(echo $val|grep 'options: '|sed 's/options: //')
  local commands="install brew init dump set_repo pull push clean update edit \
    casklist cask_upgrade test get_files commands version help"
  local commands_hyphen="-i --init -s --set_repo -c --clean -u --update -e \
    --edit --cat --test --commands -v --version -h --help"
  local options="-f --file -F --format --form -U --noupdate --preupdate -r \
    --repo -n --nolink --caskonly -C -y --yes -V --verbose"
  if [ "$1" = "commands" ];then
    echo $commands
  elif [ "$1" = "commands_hyphen" ];then
    echo $commands_hyphen
  elif [ "$1" = "options" ];then
    echo $options
  elif [ "$1" = "all_commands" ];then
    echo $commands $commands_hyphen
  else
    echo $commands $commands_hyphen $options
  fi
}

_brew_file_check_commands () {
  if [ "$ZSH_VERSION" != "" ];then
    local w
    w=("${words[@]:1}")
  else
    local w=("${COMP_WORDS[@]:1}")
  fi
  local cmds
  cmds=($(_brew_file_options all_commands))
  local c
  for c in "${w[@]}";do
    if echo " ${cmds[*]} "|grep -q " $c ";then
      echo $c
      return 0
    fi
  done
  return 1
}

_brew_file () {
  if [ "$ZSH_VERSION" != "" ];then
    local isksharrays=0
    if ! setopt|grep -q ksharrays;then
      isksharrays=1
      setopt ksharrays
    fi
    local cword=$((CURRENT-1))
    local w
    w=("${words[@]}")
  else
    local cword=$((COMP_CWORD))
    local w=("${COMP_WORDS[@]}")
  fi
  if [ $cword -gt 2 ] && [ "$1" = "brew" ] && [ "$2" = "file" ];then
    local cur=${w[cword-1]}
    local prev=${w[cword-2]}
  else
    local cur=${w[cword]}
    local prev=${w[cword-1]}
  fi
  if [ "$prev" = "-f" ];then
    if [ "$ZSH_VERSION" != "" ];then
      _files
    else
      COMPREPLY=($(compgen -f "${cur}"))
    fi
  else
    local complist=""
    if [ "$prev" = "-F" ] || [ "$prev" = "--format" ];then
      complist="file brewdler"
    elif [ "$prev" = "-V" ] || [ "$prev" = "--verbose" ];then
      complist="0 1 2"
    elif cmd=$(_brew_file_check_commands);then
      if [ "${cur:0:1}" = "-" ];then
        local minopt='-f --file -F --format -y --yes -v --verbose'
        case $cmd in
          install|pull|push|edit|-e|--edit)
            complist="$minopt --preupdate -U --noupdate";;
          brew)
            complist="$minopt";;
          init|dump|-i|--init|update|-u|--update)
            complist="$minopt -n --nolink --caskonly --preupdate -U --noupdate";;
          set_repo|-s|--set_repo)
            complist="$minopt -r --repo";;
          clean|-c|--clean)
            complist="$minopt -C";;
          cask_upgrade)
            complist="-C -y --yes -v --verbose";;
          #casklist|test|commands|--commands|version|-v|--version|help|-h|--help)
          *)
            complist=""
        esac
      else
        complist=""
      fi
    else
      complist="$(_brew_file_options commands)"
    fi
    if [ "$ZSH_VERSION" != "" ];then
      compadd $(echo $complist)
    else
      COMPREPLY=($(compgen -W "$complist" -- "${cur}"))
    fi
  fi
  if [ "$ZSH_VERSION" != "" ] && [ $isksharrays -eq 1 ];then
    unsetopt ksharrays
  fi
}

if [ "$ZSH_VERSION" != "" ];then
  compdef _brew_file brew-file
else
  complete -o default -F _brew_file brew-file
fi
