name: setup Homebrew
description: Setup Homebrew

runs:
  using: composite
  steps:
    - name: Detect Homebrew
      id: brew_env
      shell: bash
      run: |
        # Linuxbrew
        for path in "/home/linuxbrew/.linuxbrew/bin" "/opt/homebrew/bin" "/usr/local/bin";do
          if [ -x "$path/brew" ]; then
            eval "$("$path/brew" shellenv)"
            echo "$path" >>"$GITHUB_PATH"
          fi
        done

        # Keep HOMEBREW variables
        echo "HOMEBREW_PREFIX=$(brew --prefix)" >> "$GITHUB_ENV"
        echo "HOMEBREW_CELLAR=$(brew --cellar)" >> "$GITHUB_ENV"
        echo "HOMEBREW_REPOSITORY=$(brew --repository)" >> "$GITHUB_ENV"
