---
name: check

on:
#  push:
#    branches:
#      - master
#  schedule:
#      - cron:  '0 0 * * *'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  interface:
    permissions:
      contents: read
      models: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Get source
        id: source
        run: |
          echo "code<<EOF" >> "$GITHUB_OUTPUT"
          cat bin/brew-file >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: ai interface
        id: inference
        uses: actions/ai-inference@v1
        with:
          # Even with 200000 (default 200), following error:
          # Error: An error occurred trying to start process '/home/runner/runners/2.323.0/externals/node20/bin/node' with working directory '/home/runner/work/homebrew-file/homebrew-file'. Argument list too long
          max-tokens: 200000
          prompt: "Read the following code and make suggestions:\n---\n${{ steps.source.outputs.code }}"
      - name: Print Output
        id: output
        run: echo "${{ steps.inference.outputs.response }}" >> "$GITHUB_STEP_SUMMARY"
